# Generated by Django 5.0.4 on 2024-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]











